# Generated by Django 5.1 on 2024-09-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Awarded', 'Awarded')], default='Open', max_length=50)),
                ('minimum_bid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maximum_bid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('notice_file', models.FileField(max_length=150, upload_to='tender/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
