# Generated by Django 5.1 on 2024-09-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('farm_name', models.CharField(max_length=255)),
                ('farm_location', models.CharField(max_length=255)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
